#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rDrive,        tmotorVex269, openLoop)
#pragma config(Motor,  port2,           lDrive,        tmotorVex269, openLoop)
#pragma config(Motor,  port3,           rShooter,      tmotorVex269, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           lShooter,      tmotorVex269, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port5,           rIntake,       tmotorVex269, openLoop)
#pragma config(Motor,  port6,           lIntake,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true){

	}

}
